spring.application.name=novastep 
spring.datasource.url=${DB_URL} 
spring.datasource.username=${DB_USERNAME} 
spring.datasource.password=${DB_PASSWORD} 
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver 
spring.jpa.hibernate.ddl-auto=none 
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect 
jwt.secret=${JWT_SECRET} 
jwt.expiration=3600000 
server.port=${PORT:8080}